sx, sy = guiGetScreenSize()

defPositions = {
    ["oocchat"] = {
        ["name"] = "OOC Chat",
        ["turnable"] = true,
        ["showing"] = true,
		["sizeable"] = true,
		["width"] = 500,
		["height"] = 140,
        ["minWidth"] = 350,
        ["minHeight"] = 100,
        ["maxWidth"] = 500 * 1.5,
        ["maxHeight"] = 150 * 2,
		["x"] = 20,
		["y"] = 330,
    },
    
    ["chat"] = {
        ["name"] = "IC Chat",
        ["turnable"] = true,
        ["showing"] = false,
		["sizeable"] = true,
		["width"] = 500,
		["height"] = 280,
        ["minWidth"] = 500 * 0.5,
        ["minHeight"] = 290 * 0.5 - 10,
        ["maxWidth"] = 500 * 1.5,
        ["maxHeight"] = 290 * 1.5,
		["x"] = 20,
		["y"] = 16,
    },
    
    ["hudmoney"] = {
        ["name"] = "Pénz",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 150,
		["height"] = 25,
		["x"] = sx - 255,
		["y"] = 120,
    },
    ["infobox"] = {
        ["name"] = "Infobox",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 420,
		["height"] = 35,
		["x"] = sx/2 - 395/2,
		["y"] = 10,
    },
    ["kick/ban"] = {
        ["name"] = "Adminbox",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 340,
		["height"] = 47*3,
		["x"] = 20,
		["y"] = sy - 305 - (47*2),
    },
    ["oxygen"] = {
        ["invisible"] = false,
        ["name"] = "Oxigén",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 310,
		["height"] = 10,
		["x"] = sx/2 - 310/2,
		["y"] = sy - 10 - 90,
        ["sizeable"] = true,
        ["minWidth"] = 50,
        ["minHeight"] = 10,
        ["maxWidth"] = 600,
        ["maxHeight"] = 20,
    },
    ["bone"] = {
        ["invisible"] = false,
        ["name"] = "",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 18,
		["height"] = 46,
		["x"] = sx - 150,
		["y"] = 140,
    },
    ["speedo"] = {
        ["name"] = "Kilóméteróra",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 275,
		["height"] = 275,
		["x"] = sx - 20 - 275,
		["y"] = sy - 20 - 20 - 275,
    },
    ["vehname"] = {
        ["name"] = "Járműnév",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 300,
		["height"] = 30,
		["x"] = sx - 20 - 300,
		["y"] = sy - 20 - 280 - 30,
    },
    ["handbrake"] = {
        ["invisible"] = true,
        ["name"] = "Kézifék",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 64,
		["height"] = 256,
		["x"] = sx - 20 - 64,
		["y"] = sy/2 - 20 - 256/2,
    },
    ["km counter"] = {
        ["invisible"] = true,
        ["name"] = "Kilóméter Számláló",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 150,
		["height"] = 50,
		["x"] = sx - 20 - 220,
		["y"] = sy - 20 - 280 - 30-55,
    },
    ["speedo_icon"] = {
        ["invisible"] = true,
        ["name"] = "Sebességmérő Ikon",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 145,
		["height"] = 90,
		["x"] = sx - 20 - 250,
		["y"] = sy - 20 - 275+160,
    },
    ["weapon"] = {
        ["name"] = "Fegyver",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 256/1.2,
		["height"] = 50,
		["x"] = sx - 500,
		["y"] = 95,
    },
    ["shopitems"] = {
        ["invisible"] = true,
        ["name"] = "Bolt Item",
        ["turnable"] = false,
        ["showing"] = true,
		["width"] = 80,
		["height"] = 70,
		["x"] = sx/2,
		["y"] = sy/2,
    },
    ["groupinfo"] = {
        ["invisible"] = true,
        ["name"] = "Csapat információk",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 250,
		["height"] = 250,
		["x"] = sx * 0.25,
		["y"] = 25,
    },
    ["packetloss"] = {
        ["name"] = "Csomagveszteség",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 180,
		["height"] = 20,
		["x"] = sx - 200,
		["y"] = 280,
    },
    ["videocard"] = {
        ["name"] = "Videókártya",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 300,
		["height"] = 100,
		["x"] = sx - 310,
		["y"] = 250,
    },
    ["premiumPoints"] = {
        ["name"] = "PP",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 180,
		["height"] = 20,
		["x"] = sx - 200,
		["y"] = 230,
    },
    ["datum"] = {
        ["name"] = "Dátum",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 100,
		["height"] = 20,
		["x"] = sx - 120,
		["y"] = 210,
    },
    ["time"] = {
        ["name"] = "Idő",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 70,
		["height"] = 20,
		["x"] = sx - 200,
		["y"] = 210,
    },
    ["name"] = {
        ["name"] = "Karakternév",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 280,
		["height"] = 30,
		["x"] = sx - 300,
		["y"] = 170,
    },
    ["fps"] = {
        ["name"] = "FPS",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 75,
		["height"] = 20,
		["x"] = sx - 95,
		["y"] = 150,
    },
    ["ping"] = {
        ["name"] = "Ping",
        ["turnable"] = true,
        ["showing"] = false,
		["width"] = 70,
		["height"] = 20,
		["x"] = sx - 200,
		["y"] = 150,
    },
    ["hp"] = {
        ["name"] = "Élet",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 90,
		["height"] = 90,
		["x"] = sx - 320,
		["y"] = 0,
    },
    ["armor"] = {
        ["name"] = "Páncél",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 90,
		["height"] = 90,
		["x"] = sx - 320 + 60,
		["y"] = 40,
    },
    ["hunger"] = {
        ["name"] = "Éhség",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 90,
		["height"] = 90,
		["x"] = sx - 320 + 120,
		["y"] = 0,
    },
    ["thirsty"] = {
        ["name"] = "Szomjúság",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 90,
		["height"] = 90,
		["x"] = sx - 320 + 180,
		["y"] = 40,
    },
    ["stamina"] = {
        ["name"] = "Stamina",
        ["turnable"] = true,
        ["showing"] = true,
		["width"] = 90,
		["height"] = 90,
		["x"] = sx - 320 + 240,
		["y"] = 0,
    },	
	-- [4] = { -- Armor
		-- ["name"] = "Armor",
		-- ["showing"] = true,
		-- ["width"] = 200,
		-- ["height"] = 100,
		-- ["x"] = 200,
		-- ["y"] = 300,
	-- },	
    
    --20, sy - 265, 350, 225, {true, true}, true, {{100, 600}, {100, 600}}
	["radar"] = { -- Radar 5
		--["name"] = "Radar",
        ["name"] = "Térkép",
        ["turnable"] = true,
		["showing"] = true,
		["sizeable"] = true,
		["width"] = 350,
		["height"] = 225,
        ["minWidth"] = 100,
        ["minHeight"] = 100,
        ["maxWidth"] = 550,
        ["maxHeight"] = 550,
		["x"] = 20,
		["y"] = sy - 245,
	},
    --[[
    ["Chat"] = { -- Radar 5
		--["name"] = "Radar",
		["showing"] = true,
		["sizeable"] = true,
		["width"] = 500,
		["height"] = 300,
        ["minWidth"] = 350,
        ["minHeight"] = 200,
        ["maxWidth"] = 1000,
        ["maxHeight"] = 700,
		["x"] = 20,
		["y"] = 16,
	},]]
    
    --20, sy/2 - (15*5)/2,310, 15*5, {false, true}, true, {{50, 600}, {15*2, 15*20}}
    --[[
    ["ooc"] = { -- Radar 5
		--["name"] = "Radar",
        ["name"] = "OOC Chat",
		["showing"] = true,
        ["turnable"] = true,
		["sizeable"] = true,
		["width"] = 310,
		["height"] = 15*5,
        ["minWidth"] = 310,
        ["minHeight"] = 15*2,
        ["maxWidth"] = 310,
        ["maxHeight"] = 15*20,
		["x"] = 20,
		["y"] = sy/2 - (15*5)/2,
	},]]
    
    ["Inventory"] = {
        ["name"] = "Leltár",
        ["showing"] = true,
        --["turnable"] = true,
        
		["width"] = 300,
		["height"] = 22, --256,
		["x"] = sx - 382 - 20,
		["y"] = sy/2 - 256/2,
        ["invisible"] = true,
    },
    
    ["Actionbar"] = {
        ["name"] = "Actionbar",
        ["showing"] = true,
        ["turnable"] = true,
		["width"] = (36 * 6 + 5 * 1) + 10,
		["height"] = 40,
		["x"] = sx/2 - (230/2),
		["y"] = sy - 50,
        ["type"] = 1, 
        ["columns"] = 6,
    },
}

--[[
for k,v in pairs(defPositions) do
    
    if v["width"] <= 42 then
        --outputChatBox(k)
        v["width"] = 42
    end
    
    if v["height"] <= 30 then
        v["height"] = 30
    end
    
    local font = exports['cr_fonts']:getFont("Rubik-Regular", 12)
    if v["width"] <= dxGetTextWidth(k, 1, font) + 10 then
        v["width"] = dxGetTextWidth(k, 1, font) + 10
    end
end]]